### ISSUE TITLE
How to evaluate the trained models?

### ISSUE THREAD

**Issue by Deepak3994** [simonmeister/motion-rcnn#3]
Hi,

I have trained your code for arround 50k steps, using the script "python train.py --logtostderr --pipeline_config_path=data/configs/motion_rcnn_vkitti_cam.config --train_dir=output/train/motion_rcnn_vkitti_cam --gpu 0".

I wanted to know how to evaluate the trained model. I ran another script "python eval.py --logtostderr --pipeline_config_path=data/configs/motion_rcnn_vkitti_cam.config --checkpoint_dir=output/train/motion_rcnn_vkitti_cam --eval_dir=output/eval/motion_rcnn_vkitti_cam", which generated few events file in the folder. 

![Screenshot from 2019-04-11 08-53-45](https://user-images.githubusercontent.com/20994657/55944083-5c1ef480-5c37-11e9-9d89-255e4aee5491.png)

Kindly help, in getting to know how can i evaluate.

**Comment by simonmeister** [comment]
Hi, you should use TensorBoard to open the logs.

**Comment by Deepak3994** [comment]
Hi,

How to do the inference?

**Comment by chowkamlee81** [comment]
Do we have any sample code to do inference on multiple images? I hope inference code is not the same as in tesnorflow object detection api... 
Kindly provide inputs...

**Comment by simonmeister** [comment]
Inference is done like in the tensorflow object detection API, sorry.
